# Generated by Django 5.2.6 on 2025-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
